### ISSUE TITLE
Cannot invoke "java.lang.Integer.intValue()" because the return value is null

### ISSUE THREAD

**Issue by WilcoM** [fantomitechno/Emotes#2]
As you mentioned in the now closed issue, the new version does no longer throw an error on the server side, and the server boots up successfully! However, when I installed the mod client side and tested if it'd work on the server, I immediately get a Network Protocol Error, with the following log:

```
---- Minecraft Network Protocol Error Report ----
// It's the tubes, they're clogged!

Time: 2024-08-02 14:53:45
Description: Packet handling error

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "dev.renoux.emotes.util.EmoteUtil.getCodepoint(String)" is null
	at net.minecraft.class_2588.redirect$zbj000$emotes$visit(class_2588.java:553)
	at net.minecraft.class_2588.method_27660(class_2588.java:185)
	at net.minecraft.class_2561.method_27658(class_2561.java:97)
	at net.minecraft.class_341.method_1850(class_341.java:25)
	at net.minecraft.class_338.method_1815(class_338.java:236)
	at net.minecraft.class_338.method_44811(class_338.java:214)
	at net.minecraft.class_338.method_1812(class_338.java:208)
	at net.minecraft.class_7594.method_45745(class_7594.java:125)
	at net.minecraft.class_7594.method_44818(class_7594.java:88)
	at net.minecraft.class_7594.method_45746(class_7594.java:123)
	at net.minecraft.class_634.method_45724(class_634.java:947)
	at net.minecraft.class_7827.method_46324(class_7827.java:25)
	at net.minecraft.class_7827.method_11054(class_7827.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:27)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2588.redirect$zbj000$emotes$visit(class_2588.java:553)
	at net.minecraft.class_2588.method_27660(class_2588.java:185)
	at net.minecraft.class_2561.method_27658(class_2561.java:97)
	at net.minecraft.class_341.method_1850(class_341.java:25)
	at net.minecraft.class_338.method_1815(class_338.java:236)
	at net.minecraft.class_338.method_44811(class_338.java:214)
	at net.minecraft.class_338.method_1812(class_338.java:208)
	at net.minecraft.class_7594.method_45745(class_7594.java:125)
	at net.minecraft.class_7594.method_44818(class_7594.java:88)
	at net.minecraft.class_7594.method_45746(class_7594.java:123)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:disguised_chat
	Is Terminal: false
	Is Skippable: true
Stacktrace:
	at net.minecraft.class_2600.method_59803(class_2600.java:56)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_59807(class_8673.java:113)
	at net.minecraft.class_2600.method_11072(class_2600.java:32)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.class_310.method_1523(class_310.java:1240)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: fabric

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1830984784 bytes (1746 MiB) / 2826960896 bytes (2696 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800 8-Core Processor              
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 12288.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5222
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 52087.45
	Virtual memory used (MiB): 20228.42
	Swap memory total (MiB): 3072.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 7042.28, total: 432109.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 7042.28, total: 432109.00
	Space in storage for io.netty.native.workdir (MiB): available: 7042.28, total: 432109.00
	Space in storage for java.io.tmpdir (MiB): available: 7042.28, total: 432109.00
	Space in storage for workdir (MiB): available: 7042.28, total: 432109.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8064M
	Fabric Mods: 
		armorposer: Armor Poser 6.0.4
		chat_heads: Chat Heads 0.12.9
		cloth-config: Cloth Config v15 15.0.128
			cloth-basic-math: cloth-basic-math 0.6.1
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		emotes: Emotes Mod Client 1.1.2
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_quiltmc_quilt-config: quilt-config 1.3.1
			org_quiltmc_quilt-config_serializers_toml: toml 1.3.1
		fabric-api: Fabric API 0.100.8+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.15+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.18+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.2+c111832ad1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.25+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.13+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.3+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.13+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.1+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.13+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.26+a5d66753d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.2.0+7e687b32d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.83+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.0
			mixinextras: MixinExtras 0.4.0
		indium: Indium 1.0.34+mc1.21
		inventoryprofilesnext: Inventory Profiles Next 2.0.3
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		libipn: libIPN 6.0.0
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
		mousetweaks: Mouse Tweaks 2.26
		placeholder-api: Placeholder API 2.4.1+1.21
		shulkerboxtooltip: Shulker Box Tooltip 5.0.4+1.21
		sodium: Sodium 0.5.11+mc1.21
		status: Status 1.21-1.0.6
		voicechat: Simple Voice Chat 1.21-2.5.19
		xaerominimap: Xaero's Minimap 24.2.1
		xaeroworldmap: Xaero's World Map 1.38.8
		xaerozoomout: XaeroZoomout 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Loaded Shaderpack: ComplementaryReimagined_r5.2.2.zip
		Profile: HIGH (+4 options changed by user)
```

**Comment by fantomitechno** [comment]
Did you modify the config with your emotes or just put it on a server and call it a day?

In the first case, it's my bad I should clearly say that you have some work to do before hand. 

In the second, could you give me your config file?

**Comment by fantomitechno** [comment]
Can I have more informations on your server config? (content of the config file and content of the emotes folder)

**Comment by WilcoM** [comment]
> Did you modify the config with your emotes or just put it on a server and call it a day?
> 
> In the first case, it's my bad I should clearly say that you have some work to do before hand.
> 
> In the second, could you give me your config file?

I'm sorry, yes, I didn't add an emote to the emotes folder, it's now there, and I no longer get the error mentioned in the title. However I do get the following error, and MC fully crashes when I try typing : in chat.

```
[21:06:55] [Render thread/INFO]: Reloading entity icon resources...
[21:06:55] [Render thread/INFO]: Reloaded entity icon resources!
[21:07:02] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:922) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_382.method_24045(net.minecraft.class_327$class_6415)" because "$$5" is null
	at net.minecraft.class_327$class_5232.accept(class_327.java:231) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27477(class_5223.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27474(class_5223.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_5481.method_30753(class_5481.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_27530(class_327.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_1723(class_327.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_22942(class_327.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51430(class_332.java:290) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_51439(class_332.java:300) ~[client-intermediary.jar:?]
	at dev.renoux.emotes.util.EmojiSuggestionHelper$EmojiSuggestions.render(EmojiSuggestionHelper.java:184) ~[emotes-1.21-1.1.2.jar:?]
	at dev.renoux.emotes.util.EmojiSuggestionHelper.render(EmojiSuggestionHelper.java:149) ~[emotes-1.21-1.1.2.jar:?]
	at net.minecraft.class_408.handler$zbk000$emotes$render(class_408.java:535) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25394(class_408.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:117) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$241(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$zno000$fabric-screen-api-v1$onRenderScreen(class_757.java:2586) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:913) ~[client-intermediary.jar:?]
	... 6 more
```

emotes.toml:
```
emotes = ["kappa:Kappa"]
```

kappa.png: ![kappa](https://github.com/user-attachments/assets/bc6ce982-2e54-417f-8cbd-f85069352f39)

**Comment by fantomitechno** [comment]
ok so I'm gonna close in favor of #3
